-- DEPRECATED: Gallery images are now uploaded via admin UI to the 'gallery' storage bucket.
-- This file is kept for reference only. Do not run on new databases.
-- Use /admin/gallery -> "Upload multiple" to seed images instead.
